### ISSUE TITLE
IETF version visualization

### ISSUE THREAD

**Issue by ekzyis** [ekzyis/ChaCha-CT2#146]
I already know that I need to update some stuff to also work with the IETF version.

For example:
- #140 Update colors depending on chosen version

I should test if there is stuff missing which I don't know of yet.

---

### TODO
Overview page:

- [x] Update color and description in state matrix
- [x] Update descriptions (counter and IV size)

State Matrix Initialization page:

- [x] Update colors in state matrix
- [x] Check if all parameters are encoded correctly
